version: '3.8'

services:
    # MySQL Database for development
    mysql-dev:
        image: mysql:8.0
        container_name: onlook-mysql-dev
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: onlook_dev_db
            MYSQL_USER: onlook_user
            MYSQL_PASSWORD: onlook_password
        ports:
            - '3307:3306' # Different port to avoid conflicts
        volumes:
            - mysql_dev_data:/var/lib/mysql
        networks:
            - onlook-dev-network
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

    # Development environment (optional)
    app-dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: deps # Only build up to deps stage for development
        container_name: onlook-app-dev
        restart: unless-stopped
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
            - DATABASE_URL=mysql://onlook_user:onlook_password@mysql-dev:3306/onlook_dev_db
        depends_on:
            mysql-dev:
                condition: service_healthy
        networks:
            - onlook-dev-network
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        command: npm run dev

volumes:
    mysql_dev_data:
        driver: local

networks:
    onlook-dev-network:
        driver: bridge
