import type { Metadata } from 'next';
import './globals.css';
import { AppProvider } from '../contexts/AppContext';
import { Header } from '../components/layout/Header';
import { Navigation } from '../components/layout/Navigation';
import { GlobalDialogs } from '../components/layout/GlobalDialogs';

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="c6_px-w">
            <body className="" data-oid="9i_nu4i">
                <AppProvider data-oid="4k6ysob">
                    <div className="min-h-screen bg-gray-50" data-oid="7.5.idl">
                        <Header data-oid="x6hhiwr" />
                        <Navigation data-oid="jf8vlcp" />
                        <main
                            className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
                            data-oid="e0mtr:h"
                        >
                            {children}
                        </main>
                        <GlobalDialogs data-oid="ikklz97" />
                    </div>
                </AppProvider>
            </body>
        </html>
    );
}
