import type { Metadata } from 'next';
import './globals.css';
import { AppProvider } from '../contexts/AppContext';
import { Header } from '../components/layout/Header';
import { Navigation } from '../components/layout/Navigation';
import { GlobalDialogs } from '../components/layout/GlobalDialogs';

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="_ap9_kx">
            <body className="" data-oid=".0djxkd">
                <AppProvider data-oid="admf492">
                    <div className="min-h-screen bg-gray-50" data-oid="tqe35hj">
                        <Header data-oid="xfk:j-i" />
                        <Navigation data-oid="ytrz1.." />
                        <main
                            className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
                            data-oid="97g72il"
                        >
                            {children}
                        </main>
                        <GlobalDialogs data-oid=".ih4-hw" />
                    </div>
                </AppProvider>
            </body>
        </html>
    );
}
